# Generated by Django 5.2.15 on 2026-06-08 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(editable=False, max_length=20, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('receipt_date', models.DateTimeField(auto_now_add=True)),
                ('promised_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('draft', 'Received'), ('diagnosis', 'In Diagnosis'), ('quote', 'Quotation Sent'), ('workorder', 'Work in Progress'), ('done', 'Done'), ('cancel', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetailLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_detail', models.CharField(max_length=100)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.jobcard')),
            ],
        ),
    ]
