# Generated by Django 5.2.15 on 2026-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='receipt_date',
            field=models.DateTimeField(),
        ),
    ]
