# Generated by Django 5.2.15 on 2026-06-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('workshop', '0003_alter_receipt_date_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='contacts.customer',
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Customer',
                ),
            ],
            database_operations=[],
        ),
    ]
