# Generated by Django 5.2.15 on 2026-06-12 12:39

import django.db.models.deletion
from django.db import migrations, models


def migrate_jobcard_vehicles(apps, schema_editor):
    JobCard = apps.get_model('workshop', 'JobCard')
    Vehicle = apps.get_model('fleet', 'Vehicle')
    VehicleBrand = apps.get_model('fleet', 'VehicleBrand')
    VehicleModel = apps.get_model('fleet', 'VehicleModel')

    unknown_brand, _ = VehicleBrand.objects.get_or_create(name='Unknown')
    unknown_model, _ = VehicleModel.objects.get_or_create(
        brand=unknown_brand,
        name='Unknown',
    )

    for job_card in JobCard.objects.filter(vehicle__isnull=True):
        plate = (getattr(job_card, 'license_plate', '') or '').strip()
        chassis = (getattr(job_card, 'vin', '') or '').strip()
        if not plate and not chassis:
            continue

        vehicle = None
        if plate:
            vehicle = Vehicle.objects.filter(license_plate__iexact=plate).first()
        if not vehicle and chassis:
            vehicle = Vehicle.objects.filter(chassis_number__iexact=chassis).first()
        if not vehicle:
            vehicle = Vehicle.objects.create(
                customer=job_card.customer,
                brand=unknown_brand,
                model=unknown_model,
                license_plate=plate,
                chassis_number=chassis,
            )

        job_card.vehicle = vehicle
        job_card.save(update_fields=['vehicle'])


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('workshop', '0004_alter_jobcard_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KMS'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='fleet.vehicle',
            ),
        ),
        migrations.RunPython(migrate_jobcard_vehicles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='jobcard',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vin',
        ),
    ]
