# Generated by Django 5.2.15 on 2026-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Customer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('phone', models.CharField(blank=True, default='', max_length=100)),
                        ('email', models.EmailField(blank=True, default='', max_length=100)),
                    ],
                    options={
                        'db_table': 'workshop_customer',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
